---
- name: Update repositories cache and install dependency packages
  ansible.builtin.apt:
    pkg:
    - cmake 
    - pkg-config 
    - libfreetype6-dev 
    - libfontconfig1-dev 
    - libxcb-xfixes0-dev 
    - libxkbcommon-dev
    - python3
    update_cache: yes

# https://github.com/alacritty/alacritty