---
- name: Update repositories cache and install dependency packages
  ansible.builtin.apt:
    pkg:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev 
    - libsqlite3-dev
    - git
    - llvm 
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
    - libsasl2-dev
    - python3-dev
    - libldap2-dev
    update_cache: yes

- name: Download pyenv
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.sh

- name: Run pyenv
  ansible.builtin.shell:
    cmd: /usr/bin/bash /tmp/pyenv.sh
    creates: /root/.pyenv

- name: Add env to .bashrc 
  ansible.builtin.blockinfile: 
    path: $HOME/.bashrc 
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: Add env to .profile 
  ansible.builtin.blockinfile: 
    path: $HOME/.profile 
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: Refresh .profile and .bashrc
  ansible.builtin.shell:
    cmd: | 
      . ~/.profile
      . ~/.bashrc

- name: Install python
  ansible.builtin.shell:
    cmd: /root/.pyenv/bin/pyenv install 3.10.4
    creates: /root/.pyenv/versions/3.10.4 

- name: Use python
  ansible.builtin.shell:
    cmd: /root/.pyenv/bin/pyenv global 3.10.4
