---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule_kubernetes
    image: centos:centos8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
